// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywyjhqbmmvlexkbkfqeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eWpocWJtbXZsZXhrYmtmcWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzk5OTAsImV4cCI6MjA1Njg1NTk5MH0.hVIf6qzB-P9sbR11w1MVcNQN1N4QUT1Pt9txBXdihYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);